- name: Copy MongoDb Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Server
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Replace Listen Address in MongoDB
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes