- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: java.yml

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.vinithaws.online -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load App User
  ansible.builtin.shell: mysql -h mysql-dev.vinithaws.online -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load Master Data
  ansible.builtin.shell: mysql -h mysql-dev.vinithaws.online -uroot -pRoboShop@1 < /app/db/master-data.sql